src/main/java/se/esss/ics/iocfactory/model/AuditEntry.java
/*
 * Copyright (c) 2015-2016 European Spallation Source
 * Copyright (c) 2015-2016 Cosylab d.d.
 *
 * This file is part of IOC Factory.
 *
 * IOC Factory is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the License,
 * or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.iocfactory.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * A model value class that represents an Audit entry for an IOC
 *
 * @author <a href="mailto:miroslav.pavleski@cosylab.com">Miroslav Pavleski</a>
 */
public class AuditEntry implements Serializable, HasConsistencyStatus {
    /** used as unique id in the UI logic, not as a db key */
    private final String id;
    private final IOC ioc;
    private final String environment;
    private final GenerateEntry generateEntry;
    private boolean configDifferent = true;
    private Date diskModificationTime = null;

    private final ConsistencyStatusSet consistencyStatus = new ConsistencyStatusSet();

    /** Constructor needed for view state save restore */
    public AuditEntry() {
        id = UUID.randomUUID().toString();
        ioc = null;
        environment = null;
        generateEntry = null;
    }

    /**
     * Constructs an entity with all fields initialized
     *
     * @param ioc
     * @param environment
     * @param generateEntry
     *            optional can be {@code null} to signify that there is no generate entry for this IOC
     */
    public AuditEntry(IOC ioc, String environment, GenerateEntry generateEntry) {
        this.id = UUID.randomUUID().toString();
        this.ioc = ioc;
        this.environment = environment;
        this.generateEntry = generateEntry;
    }

    public String getId() {
        return id;
    }

    public IOC getIoc() {
        return ioc;
    }

    public String getEnvironment() {
        return environment;
    }

    public GenerateEntry getGenerateEntry() {
        return generateEntry;
    }

    public boolean isConfigDifferent() {
        return configDifferent;
    }

    public void setConfigDifferent(boolean configDifferent) {
        this.configDifferent = configDifferent;
    }

    public Date getDiskModificationTime() {
        return diskModificationTime != null ? new Date(diskModificationTime.getTime()) : null;
    }

    public void setDiskModificationTime(Date diskModificationTime) {
        this.diskModificationTime = diskModificationTime != null ? new Date(diskModificationTime.getTime()) : null;
    }

    /**
     * Shortcut getter for {@link AuditEntry#ioc} {@link IOC#getName()}
     *
     * @return the name of the ioc
     */
    public String getIocName() {
        return ioc.getName();
    }

    /**
     * Returns {@code true} if there is a generate entry for this IOC
     *
     * @return true if has generated entry, else false
     */
    public boolean hasGenerateEntry() {
        return generateEntry != null;
    }

    @Override
    public ConsistencyStatusSet getConsistencyStatus() {
        return consistencyStatus;
    }

    public List<ConfigVerifyStatus> getConfigVerifyStatus(String category) {
        return consistencyStatus.stream()
                .map(status -> new ConfigVerifyStatus(status.getLevel(), status.getDesc(), category))
                .collect(Collectors.toList());
    }
}

src/main/webapp/dialogs/generate/generate-undeploy-dialog.xhtml
<!--
 Copyright (c) 2015-2016 European Spallation Source
 Copyright (c) 2015-2016 Cosylab d.d.

 This file is part of IOC Factory.

 IOC Factory is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 2 of the License,
 or any newer version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 details.

 You should have received a copy of the GNU General Public License along with
 this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    <h:form id="#{formId}">
        <p:dialog id="#{widgetName}"
                  widgetVar="#{widgetName}"
                  header="#{title}" resizable="false" modal="true">
            <h:panelGroup layout="block" style="width: 80vw; height: 80vh">
                    <p:fieldset legend="Environment:" style="width: calc(100% - 3em);">
                        <p:dataTable id="envTable"
                                     widgetVar="#{widgetName}:envTable"
                                     value="#{generateManager.envs}"
                                     var="env"
                                     selectionMode="#{selectionMode}"
                                     selection="#{selectionProperty}"
                                     scrollable="true" style="width: 30em; margin-bottom: 1em;"
                                     rowKey="#{env.id}">
                            <p:column headerText="Name">
                                <h:outputText value="#{env.name}" />
                            </p:column>

                            <p:ajax event="rowSelect"
                                    update="#{formId}:verifyTable #{formId}:generateMessageList #{formId}:okButton"
                                    listener="#{controller.onEnvRowSelectionChange()}"/>
                            <p:ajax event="rowUnselect"
                                    update="#{formId}:verifyTable #{formId}:generateMessageList #{formId}:okButton"
                                    listener="#{controller.onEnvRowSelectionChange()}"/>
                        </p:dataTable>
                    </p:fieldset>

                    <p:fieldset legend="Description:" rendered="#{showDescription}" style="width: calc(100% - 3em);">
                        <p:inputTextarea id="desc" value="#{controller.desc}" style="width: 20em;" rendered="#{showDescription}"/>
                    </p:fieldset>

                <div style="height: 1em"/>

                <p:fieldset legend="#{controller.configListTitle}" style="width: calc(100% - 3em);">
                    <p:dataList id="generateMessageList" value="#{controller.generateMessageList}" var="line">
                        #{line}
                    </p:dataList>
                </p:fieldset>

                <div style="height: 2em"/>

                <p:fieldset id="verifyTable" legend="Verification messages:" style="width: calc(100% - 3em);">
                    <ui:include src="./verifytable.xhtml"/>
                </p:fieldset>

            </h:panelGroup>

            <f:facet name="footer">
                <p:panel styleClass="dialogButtonPanel">
                    <p:commandButton id="okButton" value="Ok" icon="ui-icon-check"
                                     disabled="#{empty selectionProperty}"
                                     action="#{controller.onConfirm}"
                                     update="generateForm:iocTbl generateForm:configTbl generateForm:configBtns"
                                     oncomplete="PF('#{widgetName}').hide(); PF('configTbl').filter();"/>
                    <p:commandButton value="Cancel" type="button" icon="ui-icon-close"
                                     onclick="PF('#{widgetName}').hide()" />
                </p:panel>
            </f:facet>
        </p:dialog>
    </h:form>
</ui:composition>

src/main/webapp/dialogs/generate/verifytable.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    <p:dataTable id="verifyMsgsTbl"
                 widgetVar="verifyMsgsTbl"
                 var="msg"
                 value="#{generateManager.verifyMessages}"
                 editable="false"
                 scrollable="true"
                 scrollHeight="400"
                 rowStyleClass="#{csHelper.getStatusFor(msg).rowStyle}">

        <p:column headerText="IOC Name"
                  styleClass="tbl_col_slot"
                  filterBy="#{msg.iocName}"
                  filterMatchMode="contains">
            <h:outputText value="#{msg.iocName}"/>
        </p:column>

        <p:column headerText="Revision"
                  styleClass="tbl_col_rev"
                  filterBy="#{msg.revision}"
                  filterMatchMode="contains"
                  filterStyle="width: 90%;">
            <h:outputText value="#{msg.revision}"/>
        </p:column>

        <p:column headerText="Category"
                  styleClass="tbl_col_verify_category"
                  filterBy="#{msg.category}"
                  filterMatchMode="contains"
                  filterStyle="width: 90%;">
            <h:outputText value="#{msg.category}"/>
        </p:column>

        <p:column headerText="Severity"
                  styleClass="tbl_col_verify_type"
                  filterBy="#{msg.level}"
                  filterMatchMode="contains"
                  filterStyle="width: 90%;">
            <h:outputText value="#{msg.level}"/>
        </p:column>

        <p:column headerText="Description"
                  filterBy="#{msg.desc}"
                  filterMatchMode="contains">
            <h:outputText value="#{msg.desc}"/>
        </p:column>
    </p:dataTable>
</ui:composition>